linters-setting:
  govet:
    check-shadowing: false
  gocyclo:
    min-complexity: 30
  misspell:
    locale: 'US'

linters:
  disable-all: true
  enable:
    - goimports
    - deadcode
    - errcheck
    - gocognit
    - gocritic
    - gofmt
    - govet
    - gocyclo
    - misspell
    - staticcheck
    - whitespace
