version: '3.9'
services:
  app:
    image: st-go-web-dev
    build:
      # ここでDockerfileのあるディレクトリを指定する
      args:
        - target=dev
    environment:
      ENV: dev
      PORT: 8080
    volumes:
      # これはホストのカレントディレクトリをコンテナの/appにマウントする
      - .:/app
    ports:
      - '18080:8080'
