on:
  push:
    branches:
      - main
  pull_request:
name: Test

# go
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.20'
      - uses: actions/checkout@v3
      - run: go test -v ./... -coverprofile=coverage.out
      - name: report coverage
        uses: k1LoW/octocov-action@v0
